"""empty message

Revision ID: 0056b1770cc9
Revises: 37dc11f18303
Create Date: 2018-07-08 13:41:37.692905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0056b1770cc9'
down_revision = '37dc11f18303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('meals_userId_fkey', 'meals', type_='foreignkey')
    op.create_foreign_key(None, 'meals', 'users', ['user_id'], ['id'])
    op.drop_column('meals', 'userId')
    op.add_column('menus', sa.Column('meal_id', sa.Integer(), nullable=True))
    op.drop_constraint('menus_mealId_fkey', 'menus', type_='foreignkey')
    op.create_foreign_key(None, 'menus', 'meals', ['meal_id'], ['id'])
    op.drop_column('menus', 'mealId')
    op.add_column('orders', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('meal_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('orders_userId_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_mealId_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'meals', ['meal_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.drop_column('orders', 'adminId')
    op.drop_column('orders', 'mealId')
    op.drop_column('orders', 'userId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('mealId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('adminId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_mealId_fkey', 'orders', 'meals', ['mealId'], ['id'])
    op.create_foreign_key('orders_userId_fkey', 'orders', 'users', ['userId'], ['id'])
    op.drop_column('orders', 'user_id')
    op.drop_column('orders', 'meal_id')
    op.drop_column('orders', 'admin_id')
    op.add_column('menus', sa.Column('mealId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'menus', type_='foreignkey')
    op.create_foreign_key('menus_mealId_fkey', 'menus', 'meals', ['mealId'], ['id'])
    op.drop_column('menus', 'meal_id')
    op.add_column('meals', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'meals', type_='foreignkey')
    op.create_foreign_key('meals_userId_fkey', 'meals', 'users', ['userId'], ['id'])
    op.drop_column('meals', 'user_id')
    # ### end Alembic commands ###
