"""empty message

Revision ID: 37dc11f18303
Revises: edc0a6ab553d
Create Date: 2018-06-17 15:19:50.567904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37dc11f18303'
down_revision = 'edc0a6ab553d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.String(), nullable=True))
    op.drop_column('users', 'isAdmin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isAdmin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
