"""empty message

Revision ID: 71b81d642b50
Revises: 529df88f22dd
Create Date: 2018-08-21 13:47:31.661872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b81d642b50'
down_revision = '529df88f22dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('menus_menu_name_key', 'menus', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('menus_menu_name_key', 'menus', ['menu_name'])
    # ### end Alembic commands ###
