"""empty message

Revision ID: 952a91da6b81
Revises: 71b81d642b50
Create Date: 2018-08-21 14:39:54.618418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '952a91da6b81'
down_revision = '71b81d642b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('admin_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menus', 'admin_id')
    # ### end Alembic commands ###
