"""empty message

Revision ID: b6fa43ed328f
Revises:
Create Date: 2018-07-10 22:07:07.397714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6fa43ed328f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=25), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('password', sa.String(length=25), nullable=True),
                    sa.Column('is_admin', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('meals',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('meal_name', sa.String(length=25), nullable=True),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('menus',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('meal_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('orders',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('meal_id', sa.Integer(), nullable=True),
                    sa.Column('customer_id', sa.Integer(), nullable=True),
                    sa.Column('admin_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('menus')
    op.drop_table('meals')
    op.drop_table('users')
    # ### end Alembic commands ###
